### ISSUE TITLE
Interface naming, usage  & placement needs to be changed

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/Thali_CordovaPlugin_BtLibrary#7] opened 2015-08-26 13:11 UTC
We need to change the Callback-interface to be named something more specific.

We need to implement the interface outside the class definition for the plugin entry point

We should re-use the interfaces, and remove any interfaces that implement similar functionality.

**Comment by tompaana** [comment] 2015-11-17 15:03
Duplicate of #17

**Comment by tompaana** [comment] 2015-12-02 14:38
All taken care of by #17

**Closed as completed** 2016-08-23 22:39 UTC
Labels: duplicate
